/**
 * Données temporaires de la galerie. Les visuels sont des images générées
 * (couleurs et formes de la charte graphique) en attendant le reportage
 * photo officiel du restaurant.
 */

export type GalleryCategory =
  | "plats"
  | "espaces"
  | "boissons"
  | "evenements"
  | "decoration"
  | "equipe";

export type GalleryItem = {
  id: string;
  src: string;
  alt: string;
  caption: string;
  category: GalleryCategory;
  width: number;
  height: number;
  tone?: "clair" | "sombre";
};

export const GALLERY_FILTERS: {
  value: "tout" | GalleryCategory;
  label: string;
}[] = [
  { value: "tout", label: "Tout" },
  { value: "plats", label: "Nos plats" },
  { value: "espaces", label: "Nos espaces" },
  { value: "boissons", label: "Boissons" },
  { value: "evenements", label: "Événements" },
  { value: "decoration", label: "Décoration" },
  { value: "equipe", label: "Notre équipe" },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  // plats
  {
    id: "g-plat-garba",
    src: "/images/plats/garba.jpeg",
    alt: "Garba, thon frit et attiéké",
    caption: "Garba, l'incontournable du Trophée",
    category: "plats",
    width: 1200,
    height: 1400,
  },
  {
    id: "g-plat-kedjenou",
    src: "/images/plats/kedjenou de poulet.avif",
    alt: "Kédjénou de poulet",
    caption: "Kédjénou de poulet mijoté",
    category: "plats",
    width: 1200,
    height: 1000,
  },
  {
    id: "g-plat-poisson",
    src: "/images/plats/pechedujour1.jpg",
    alt: "Poisson braisé et attiéké",
    caption: "Poisson braisé, sauce piquante maison",
    category: "plats",
    width: 1200,
    height: 1000,
  },
  {
    id: "g-plat-alloco",
    src: "/images/plats/alloco-x.jpg",
    alt: "Alloco doré",
    caption: "Alloco doré à souhait",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-sauce-graine",
    src: "/images/plats/La-sauce-graine-ivoirienne.jpg",
    alt: "Sauce graine traditionnelle",
    caption: "Sauce graine, recette traditionnelle",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-beignets",
    src: "/images/plats/neems2.jpeg",
    alt: "Neems",
    caption: "Beignets sucrés faits maison",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-1",
    src: "/images/gallerie/plats/plat1.jpeg",
    alt: "plat1",
    caption: "Plat 1",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-2",
    src: "/images/gallerie/plats/plat2.jpeg",
    alt: "plat2",
    caption: "Plat 2",
    category: "plats",
    width: 1200,
    height: 1400,
  },
  {
    id: "g-plat-3",
    src: "/images/gallerie/plats/plat3.jpeg",
    alt: "plat3",
    caption: "Plat 3",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-4",
    src: "/images/gallerie/plats/plat4.jpeg",
    alt: "plat4",
    caption: "Plat 4",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-5",
    src: "/images/gallerie/plats/plat5.jpeg",
    alt: "plat5",
    caption: "Plat 5",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-6",
    src: "/images/gallerie/plats/plat6.jpeg",
    alt: "plat6",
    caption: "Plat 6",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-8",
    src: "/images/gallerie/plats/plat8.jpeg",
    alt: "plat8",
    caption: "Plat 8",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-9",
    src: "/images/gallerie/plats/plat9.jpeg",
    alt: "plat9",
    caption: "Plat 9",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-10",
    src: "/images/gallerie/plats/plat10.jpeg",
    alt: "plat10",
    caption: "Plat 10",
    category: "plats",
    width: 1000,
    height: 900,
  },
  {
    id: "g-plat-11",
    src: "/images/gallerie/plats/plat11.jpeg",
    alt: "plat11",
    caption: "Plat 11",
    category: "plats",
    width: 1000,
    height: 900,
  },
  //espaces
  {
    id: "g-espace-interieur",
    src: "/images/espaces/espace4.jpeg",
    alt: "Salle intérieure du restaurant",
    caption: "Notre salle intérieure",
    category: "espaces",
    width: 1200,
    height: 900,
  },
  {
    id: "g-espace-exterieur",
    src: "/images/espaces/espace1.jpeg",
    alt: "Terrasse extérieure du restaurant",
    caption: "Notre terrasse extérieure",
    category: "espaces",
    width: 1200,
    height: 900,
  },
  {
    id: "g-espace-bar",
    src: "/images/espaces/bar1.jpeg",
    alt: "Bar du restaurant",
    caption: "Notre bar",
    category: "espaces",
    width: 1000,
    height: 1250,
  },
  {
    id: "g-espace-3",
    src: "/images/espaces/espace3.jpeg",
    alt: "Terrasse du restaurant en soirée",
    caption: "La terrasse en soirée",
    category: "espaces",
    width: 1200,
    height: 900,
  },
   {
    id: "g-espace-5",
    src: "/images/espaces/espace5.JPG",
    alt: "Terrasse du restaurant en soirée",
    caption: "La terrasse en soirée",
    category: "espaces",
    width: 1200,
    height: 900,
  },
   {
    id: "g-espace-6r",
    src: "/images/espaces/espace6.JPG",
    alt: "Terrasse du restaurant en soirée",
    caption: "La terrasse en soirée",
    category: "espaces",
    width: 1200,
    height: 900,
  },
  //boisson
  {
    id: "g-boisson-tipunch",
    src: "/images/boissons/mon soleil.jpeg",
    alt: "MOn Soleil, cocktail ivoirien",
    caption: "Mon Soleil",
    category: "boissons",
    width: 900,
    height: 1100,
  },
  {
    id: "g-boisson-bissap",
    src: "/images/boissons/bissap.jpeg",
    alt: "Bissap glacé",
    caption: "Bissap glacé maison",
    category: "boissons",
    width: 900,
    height: 1100,
  },
  {
    id: "g-boisson-cafe",
    src: "/images/boissons/shotbaddies.jpeg",
    alt: "Shot Baddies",
    caption: "Shot Baddies",
    category: "boissons",
    width: 900,
    height: 1100,
  },
  {
    id: "g-boisson-1",
    src: "/images/boissons/boisson1.jpeg",
    alt: "Shot Baddies vert ",
    caption: "Shot Baddies vert ",
    category: "boissons",
    width: 900,
    height: 1100,
  },
  {
    id: "g-boisson-2",
    src: "/images/boissons/boisson2.jpeg",
    alt: "boisson2",
    caption: "Shot Baddies rouge ",
    category: "boissons",
    width: 900,
    height: 1100,
  },
   {
    id: "g-boisson-3",
    src: "/images/boissons/boisson3.jpeg",
    alt: "boisson3",
    caption: "Shot Baddies vert ",
    category: "boissons",
    width: 900,
    height: 1100,
  },
   {
    id: "g-boisson-4",
    src: "/images/boissons/boisson4.jpeg",
    alt: "boisson4",
    caption: "boisson4",
    category: "boissons",
    width: 900,
    height: 1100,
  },

  //evenements
  {
    id: "g-evenement-karaoke",
    src: "/images/evenements/karaoke.png",
    alt: "Soirée karaoké au restaurant",
    caption: "Soirée karaoké",
    category: "evenements",
    width: 1200,
    height: 900,
  },
  {
    id: "g-evenement-jeux",
    src: "/images/evenements/secrethitler.jpg",
    alt: "SOiree jeux de société",
    caption: "Secret Hitler, soirée jeux de société",
    category: "evenements",
    width: 1200,
    height: 900,
  },
  {
    id: "g-evenement-match",
    src: "/images/evenements/evenement-match.jpg",
    alt: "Diffusion d'un match au restaurant",
    caption: "Diffusion d'un match",
    category: "evenements",
    width: 1200,
    height: 900,
  },
  {
    id: "g-evenement-prive",
    src: "/images/evenements/evenement-prive.jpg",
    alt: "Événement privé au restaurant",
    caption: "Anniversaire et événement privé",
    category: "evenements",
    width: 1200,
    height: 900,
  },
  //decorations
  {
    id: "g-decoration-bogolan-1",
    src: "/images/bogolan/bogolan-1.jpg",
    alt: "Bogolan aux bandes ocre, noires et ivoire exposé au restaurant",
    caption: "Bogolan aux motifs traditionnels",
    category: "decoration",
    width: 1350,
    height: 1800,
  },
  {
    id: "g-decoration-bogolan-2",
    src: "/images/bogolan/bogolan-2.jpg",
    alt: "Bogolan aux bandes indigo, ocre et ivoire exposé au restaurant",
    caption: "Bogolan indigo et ocre",
    category: "decoration",
    width: 1350,
    height: 1800,
  },
  {
    id: "g-decoration-bogolan-3",
    src: "/images/bogolan/bogolan-3.jpg",
    alt: "Bogolan brun orné de fins motifs géométriques ivoire",
    caption: "Bogolan brun aux motifs géométriques",
    category: "decoration",
    width: 1350,
    height: 1800,
  },
  {
    id: "g-decoration-bogolan-4",
    src: "/images/bogolan/bogolan-4.jpg",
    alt: "Bogolan noir et ivoire à rayures verticales exposé au restaurant",
    caption: "Bogolan noir et ivoire",
    category: "decoration",
    width: 1350,
    height: 1800,
  },
  {
    id: "g-decoration-bogolan-5",
    src: "/images/bogolan/bogolan-5.jpg",
    alt: "Bogolan brun décoré de grands symboles géométriques ivoire",
    caption: "Bogolan brun et ivoire",
    category: "decoration",
    width: 1350,
    height: 1800,
  },
  {
    id: "g-decoration-poupee-1",
    src: "/images/poupee-africaine-1.jpeg",
    alt: "Poupée africaine faisant partie de la décoration",
    caption: "L'une de nos poupées africaines",
    category: "decoration",
    width: 700,
    height: 1100,
    tone: "sombre",
  },
  {
    id: "g-decoration-poupee-2",
    src: "/images/poupee-africaine-2.jpeg",
    alt: "Poupée africaine en situation dans le décor",
    caption: "Poupée africaine, dans son décor",
    category: "decoration",
    width: 700,
    height: 1100,
    tone: "sombre",
  },
  {
    id: "g-decoration-poupee-3",
    src: "/images/poupee-africaine-1.jpeg",
    alt: "Poupée africaine, signature du restaurant",
    caption: "Poupée africaine, signature du lieu",
    category: "decoration",
    width: 700,
    height: 1100,
    tone: "sombre",
  },
    {
    id: "g-decoration-2",
    src: "/images/decoration/2.jpeg",
    alt: "jeux africain",
    caption: "jeux africain",
    category: "decoration",
    width: 1000,
    height: 1000,
  },
    {
    id: "g-decoration-2",
    src: "/images/decoration/1.jpeg",
    alt: "jeux africain",
    caption: "jeux africain",
    category: "decoration",
    width: 1000,
    height: 1000,
  },
  {
    id: "g-decoration-7",
    src: "/images/decoration/7.png",
    alt: "tableau décoratif ",
    caption: "tableau décoratif",
    category: "decoration",
    width: 1000,
    height: 1000,
  },
   {
    id: "g-decoration-8",
    src: "/images/decoration/8.png",
    alt: "poupee africaine",
    caption: "poupee africaine",
    category: "decoration",
    width: 1000,
    height: 1000,
  },
  
  // equipes
  {
    id: "g-equipe-salle",
    src: "/images/equipe/equipe-1.jpg",
    alt: "L'équipe en salle",
    caption: "L'équipe en salle",
    category: "equipe",
    width: 900,
    height: 1100,
  },
  {
    id: "g-equipe-cuisine",
    src: "/images/equipe/equipe-2.jpg",
    alt: "L'équipe en cuisine",
    caption: "L'équipe en cuisine",
    category: "equipe",
    width: 900,
    height: 1100,
  },
  {
    id: "g-equipe-accueil",
    src: "/images/equipe/equipe-3.jpg",
    alt: "L'équipe à l'accueil",
    caption: "L'accueil du restaurant",
    category: "equipe",
    width: 900,
    height: 1100,
  },
];
